import type {Metadata} from "next";
import Link from "next/link";
import {ArrowLeft} from "lucide-react";
import {SiteHeader} from "@/components/site-header";
import {entries,edition} from "@/lib/annals";
export const metadata:Metadata={title:"Edition & sources",description:"Scope, original sources, translation method, and review status of the independent Sillok English reading edition."};
export default function About(){
  const reviewed=entries.filter(e=>e.reviewStatus!=="draft").length;
  const reigns=[...new Set(entries.map(e=>e.king))];
  return <><SiteHeader current="about"/><main className="about-main"><Link className="back-link" href="/"><ArrowLeft size={16}/>Reading room</Link><p className="eyebrow">EDITION {edition.version} · {edition.date}</p><h1>A reading edition with a traceable source.</h1><p className="lead">The annals record court decisions, ordinary routines, and extraordinary events. This project makes selected entries available in new English translations, with the original text always close at hand.</p>
    <div className="scope-grid"><div><strong>{entries.length}</strong><span>complete entries translated</span></div><div><strong>{reigns.length}</strong><span>reigns represented</span></div><div><strong>{reviewed}</strong><span>independently reviewed</span></div></div>
    <div className="review-notice"><p><strong>This is an early reading edition, not a complete or authoritative translation.</strong> The initial 60 translations and reading notes were AI-generated. Each entry displays its current translation method, contributor credit, and independent review status. Community language review and specialist review of the full original are different scopes.</p></div>
    <section><h2>What is included</h2><p>This release contains {entries.length} individually sourced entries from {reigns.join(", ")}. The selection is intended to exercise the reading and translation workflow; it is not a representative statistical sample of the whole annals. Search covers only these published entries.</p><p>The initial pilot target is {edition.target} translated entries. Untranslated source candidates and the wider annals are not counted as completed translations. The complete collection, later editions, and the Gojong and Sunjong records are not reproduced here.</p></section>
    <section><h2>How to read an entry</h2><h3>English and original text</h3><p>“Parallel text” shows a new English translation beside the Classical Chinese source. English titles and topic labels are editorial additions. Reading notes explain a term or a translation choice; they are not part of the historical record.</p><h3>Dates and precision</h3><p>Year, month, and day follow the annals’ original lunisolar dating. The displayed Western year is the year label used by the official archive, not a conversion of the month and day into the Gregorian calendar. Intercalary months are identified. Sexagenary day headings are transcribed in the date metadata; volume-end colophons are retained and translated. When the text says “this month,” the edition preserves that uncertainty even if the archive files the entry under the last day of the month.</p><h3>What the record establishes</h3><p>A statement in the annals is evidence of what was recorded. It does not automatically establish that every reported event happened exactly as described. The king’s speech, a petition, an observation, and the compilers’ judgment must be read in their own contexts.</p></section>
    <section><h2>Translation method</h2><ol><li>Retrieve the individual article from the official archive and preserve its identifier, date, and original text.</li><li>Translate the complete source text into English. Keep numbers, negation, named people, and attributed speech explicit. Do not insert historical explanations into the translated text.</li><li>Record difficult terms and editorial choices in separate reading notes. Preserve original terms when a modern English equivalent would mislead.</li><li>Check the source and translation for missing passages, unintended additions, date errors, and inconsistent terminology.</li><li>Keep the “Unreviewed” label until an independent qualified reviewer has checked and approved the entry.</li></ol><p>Source matching and structural checks do not certify translation accuracy. No numerical accuracy score or claim of expert verification is made for this release.</p></section>
    <section><h2>Sources and reuse</h2><p>The Classical Chinese texts come from the <a href="https://sillok.history.go.kr/" target="_blank" rel="noreferrer">National Institute of Korean History’s Joseon annals archive</a>. Each entry links directly to its source. The source pages display a Korean Open Government License reuse mark for the original text. See the archive’s <a href="https://sillok.history.go.kr/intro/people.do" target="_blank" rel="noreferrer">2025 service update and source-rights information</a>.</p><p>Modern Korean translations and the official English translations have not been republished in this edition. Their rights and the official archive’s rights remain with their respective holders. The English translations and notes here were newly generated for this project; changes are not endorsed by the source institution.</p><p>You can also consult the official <a href="https://sillok.history.go.kr/eslk/" target="_blank" rel="noreferrer">English Sejong annals</a>. This project is independent and is not an official National Institute of Korean History publication.</p></section>
    <section><h2>Built through public contributions</h2><p>Contributors work on one complete article, record their AI usage, and submit a small pull request. Automated checks verify the file structure and source fingerprint. Registered independent reviewers provide public evidence tied to the exact source and translation. Editing a reviewed translation removes its current review status until the new version is approved.</p><p><Link href="/contribute">Choose a translation or review task</Link>. The project package contains contribution instructions, validation tools, and the review policy. Project code is MIT; new English translations and notes are <a href="https://creativecommons.org/licenses/by-sa/4.0/" target="_blank" rel="noreferrer">CC BY-SA 4.0</a> to the extent contributors hold applicable rights. Original-source rights are separate.</p></section><section><h2>Inspection and citation</h2><p>Every entry has a permanent page and a copyable citation including its source identifier, edition version, and review status. The machine-readable edition includes original-text fingerprints and retrieval dates so later changes can be checked.</p><p><a href="/api/edition" download={`sillok-edition-${edition.version}.json`}>Download this edition as JSON</a></p><p>For scholarly use, consult the original source and seek qualified review of the relevant passage. The draft label should remain attached when quoting this edition.</p></section>
  </main></>;
}
