import type {Metadata} from "next";
import Link from "next/link";
import {ArrowUpRight,Download} from "lucide-react";
import {SiteHeader} from "@/components/site-header";
import {WorkBoard,type Task} from "@/components/work-board";
import prepared from "@/data/tasks.json";
import {entries,getEntry} from "@/lib/annals";
import {githubUrl,project} from "@/lib/project";
export const metadata:Metadata={title:"Contribute one entry",description:"Bring your own AI to translate and review the Joseon annals, one source-linked article and one pull request at a time."};
export default async function Contribute({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
  const params=await searchParams;const id=typeof params.entry==="string"?params.entry:"";
  const tasks:Task[]=[...prepared].sort((a,b)=>a.kind===b.kind?(a.kind==="translate"?a.characters-b.characters:0):a.kind==="translate"?-1:1);
  const entry=getEntry(id);if(entry&&!tasks.some(t=>t.id===id))tasks.unshift({id:entry.id,kind:"review",title:entry.title,king:entry.king,year:entry.year,month:entry.month,day:entry.day,ordinal:entry.ordinal,characters:[...entry.original].length});
  const reviewed=entries.filter(e=>e.reviewStatus!=="draft").length;
  return <><a href="#contribution-main" className="skip-link">Skip to contribution tasks</a><SiteHeader current="contribute"/><main id="contribution-main" className="contribute-main"><section className="contribute-intro"><div><p className="eyebrow">OPEN SILLOK · A COMMUNITY EDITION</p><h1>One entry.<br/>A shared history.</h1><p>Help make the Joseon annals readable in English. Bring your AI, follow the original, and contribute a small, thoughtful translation.</p><div className="intro-links">{githubUrl?<a className="primary-action" href={githubUrl} target="_blank" rel="noreferrer">Contribute on GitHub <ArrowUpRight size={16}/></a>:<a className="secondary-action" href="/downloads/open-sillok-source.zip" download><Download size={16}/>Download the project</a>}<Link className="text-link" href="/about">Read the source policy <ArrowUpRight size={15}/></Link></div></div><div className="contribution-progress"><p className="column-label">THE FIRST {project.pilotTarget} ENTRIES</p><strong>{entries.length}<span> / {project.pilotTarget}</span></strong><progress value={entries.length} max={project.pilotTarget} aria-label={`${entries.length} of ${project.pilotTarget} pilot entries translated`}/><p>{entries.length-reviewed} drafts · {reviewed} independently reviewed</p><span>A pilot, not the complete annals.</span></div></section>
    {!githubUrl&&<div className="launch-note"><strong>Preparing for GitHub launch.</strong> The source package and work packs are available now. Public PR submissions will open when the repository is published.</div>}
    <div className="section-heading"><div><p className="eyebrow">START WITH A SMALL SOURCE</p><h2>Choose your first contribution</h2></div><p>{tasks.filter(t=>t.kind==="translate").length} prepared translation tasks<br/>{tasks.filter(t=>t.kind==="review").length} suggested draft reviews</p></div><WorkBoard tasks={tasks} initialId={tasks.some(t=>t.id===id)?id:tasks[0]?.id??""}/>
    <section className="contribution-principles"><div><span>01</span><h3>Every clause matters</h3><p>Translate the full original. Preserve speakers, dates, names, numbers, and uncertainty. Put explanations in separate notes.</p></div><div><span>02</span><h3>Credit travels with the text</h3><p>Record your handle and AI usage. Keep earlier contributors. New English content is CC BY-SA 4.0; project code is MIT.</p></div><div><span>03</span><h3>Review is a separate step</h3><p>Automated checks verify structure and source fingerprints. Registered independent reviewers assess language or the full original, with their scope shown.</p></div></section><p className="contribution-foot">The project package includes CONTRIBUTING.md, AI instructions, the translation guide, and local checking tools. <Link href="/">Explore the reading room <ArrowUpRight size={14}/></Link></p></main></>;
}
