"use client";
import {useMemo,useState} from "react";
import Link from "next/link";
import {ArrowUpRight,Check,Copy,Download,FileText,Search} from "lucide-react";
import {claimUrl,contributionPath,githubUrl} from "@/lib/project";
export type Task={id:string;kind:string;title:string;king:string;year:number;month:number;day:number;ordinal:number;characters:number};
export function WorkBoard({tasks,initialId}:{tasks:Task[];initialId:string}){
  const [kind,setKind]=useState("all"),[query,setQuery]=useState(""),[selectedId,setSelectedId]=useState(initialId),[copyState,setCopyState]=useState("");
  const matches=useMemo(()=>tasks.filter(t=>(kind==="all"||t.kind===kind)&&`${t.id} ${t.title} ${t.king}`.toLowerCase().includes(query.toLowerCase().trim())),[tasks,kind,query]);
  const selected=matches.find(t=>t.id===selectedId)??matches[0];
  const prompt=selected?`Contribute to Open Sillok, article ${selected.id}. I will attach the downloaded work pack. Read its instructions and complete Classical Chinese original. ${selected.kind==="review"?"Check the existing English against every source clause and propose a careful revision.":"Translate the complete original into clear English."} Keep explanations and uncertain readings in separate notes. Do not copy modern Korean or official English translations. Ask for my GitHub handle and record the actual AI model (or not-recorded), method and dates. Preserve previous credit. Return only the translation object for ${contributionPath(selected.id)}. Do not change the original, source fingerprint, validation rules or review status. Before finishing, report omissions checked, ambiguous terms and unresolved questions. AI self-checking is not independent human review.`:"";
  const choose=(id:string)=>{setSelectedId(id);setCopyState("");window.history.replaceState(window.history.state,"",`/contribute?entry=${id}`);if(window.matchMedia("(max-width:800px)").matches)requestAnimationFrame(()=>{const heading=document.getElementById("work-title");heading?.focus({preventScroll:true});heading?.scrollIntoView({behavior:window.matchMedia("(prefers-reduced-motion: reduce)").matches?"auto":"smooth",block:"start"});});};
  const copy=async()=>{try{await navigator.clipboard.writeText(prompt);setCopyState("Copied. Attach the downloaded work pack to your AI.");}catch{setCopyState("Select and copy the instructions below.");document.querySelector<HTMLTextAreaElement>("#ai-prompt")?.select();}};
  return <div className="work-board"><div className="work-list"><div className="task-filters" aria-label="Task type">{[["all","All work"],["translate","Translate"],["review","Review"]].map(([value,label])=><button key={value} aria-pressed={kind===value} onClick={()=>{setKind(value);setCopyState("");}}>{label}</button>)}</div><label className="search-box"><Search size={17}/><input type="search" aria-label="Find a task" placeholder="Find a reign or article ID" value={query} onChange={e=>{setQuery(e.target.value);setCopyState("");}}/></label><p className="task-count" aria-live="polite">{matches.length} prepared {matches.length===1?"task":"tasks"} · check GitHub before claiming</p><div className="task-items">{matches.map(t=><button key={t.id} className={`task-row ${selected?.id===t.id?"selected":""}`} aria-pressed={selected?.id===t.id} onClick={()=>choose(t.id)}><span className={`task-kind ${t.kind}`}>{t.kind==="review"?"Review a draft":"New translation"}</span><strong>{t.title}</strong><span>{t.king} · {t.year} · {t.characters.toLocaleString()} source characters</span><code>{t.id}</code></button>)}{!matches.length&&<div className="empty-results"><h3>No matching tasks</h3><p>Try an article ID or a reign.</p><button onClick={()=>{setQuery("");setKind("all");}}>Show all tasks</button></div>}</div></div>
    <section className="work-detail" aria-labelledby="work-title">{selected?<><p className="eyebrow">YOUR NEXT CONTRIBUTION</p><h2 id="work-title" tabIndex={-1}>{selected.title}</h2><p className="work-id">{selected.id}</p><div className="work-source"><FileText size={19}/><p><strong>A complete, prepared source</strong><span>{selected.characters.toLocaleString()} characters · original text, archive link, fingerprint, translation template, and instructions.</span></p></div><div className="work-actions"><a className="primary-action" href={`/api/work-packs/${selected.id}`} download><Download size={17}/>Download work pack</a><a className="secondary-action" href={`https://sillok.history.go.kr/id/${selected.id}`} target="_blank" rel="noreferrer">Read the original <ArrowUpRight size={15}/></a></div><ol className="contribute-steps"><li><strong>Choose one article</strong><p>{githubUrl?<><a href={`${githubUrl}/issues?q=${encodeURIComponent(`is:open ${selected.id}`)}`} target="_blank" rel="noreferrer">Check current work</a>, then <a href={claimUrl(selected.id)!} target="_blank" rel="noreferrer">open a task issue</a>. Wait for the maintainer to confirm a claim.</>:"The GitHub repository is being prepared. You can work on a draft now; public claims and PR submissions will open with the repository."}</p></li><li><strong>Bring your own AI</strong><p>Attach the work pack and use the instructions below. Check the result yourself, and keep uncertain readings visible.</p></li><li><strong>Submit a small PR</strong><p>Save the translation object at <code>{contributionPath(selected.id)}</code>. Run the content check and describe your changes. A merge keeps the draft label until independent review is recorded.</p></li></ol><div className="prompt-heading"><label htmlFor="ai-prompt">Instructions for your AI</label><button onClick={()=>void copy()} className="text-link">{copyState.startsWith("Copied")?<Check size={15}/>:<Copy size={15}/>}Copy</button></div><textarea id="ai-prompt" readOnly value={prompt} rows={7}/><p className="copy-feedback" role="status">{copyState}</p>{selected.kind==="review"&&<Link className="text-link" href={`/entry/${selected.id}`}>Read the current draft <ArrowUpRight size={15}/></Link>}</>:<><h2 id="work-title" tabIndex={-1}>Choose a task</h2><p>Reset the filters to see prepared work.</p></>}</section></div>;
}
